services:
  - type: web
    name: vedikg-be
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: POSTGRES_URL
        scope: run
        value: ${POSTGRES_URL}
      - key: GEMINI_API_KEY
        scope: run
        value: ${GEMINI_API_KEY}
